# In _config.yml
title: Advanced Adjustment - An Introduction to Doubly Robust Methods
author: Sunay Bhat, Ayush Chatterjee, Laxman Dahal, Nathan Hoffmann, Arya Nanda
logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib