# In _config.yml
title: Advanced Adjustment - An Introduction to Doubly Robust Methods
author: S. Bhat, A. Chatterjee, L. Dahal, N. Hoffmann, A. Nanda
logo: logo.png
execute:
  timeout: -1
  execute_notebooks: force
  allow_errors: true
    